version: '3.9'

services:
  postgres:
    container_name: postgres-for-spring-test-app
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
    restart: always